local elt = {}

elt._COPYRIGHT   = 'Copyright (c) 2024 Alejandro Exojo Piqueras'
elt._DESCRIPTION = 'Template engine in pure Lua'
elt._VERSION = '0.1.0'

--- @class Chunks
-- Simple helper that provides an `append` function to hold the array of chunks
-- of literal strings and code to be generated by the `Generator`.
--- @alias Chunks.Kind `Chunks.CODE`|`Chunks.RAW`|`Chunks.ESCAPE`
local Chunks = {
    CODE = 1,
    RAW = 2,
    ESCAPE = 3,

    --- Creates a new instance.
    --- @param self Chunks
    --- @return Chunks
    new = function(self)
        return setmetatable({}, self)
    end,

    --- Appends a string to the list of chunks.
    ---
    --- The string can be one of four kinds.
    ---  * A literal string to be put in the output verbatim.
    ---  * A fragment of Lua code to be inserted as is (`Chunks.CODE`).
    ---  * A value to be printed verbatim after converted to string (`Chunks.RAW`).
    ---  * A value to be printed after escaping (`Chunks.ESCAPE`).
    --- The last 3 require a numeric position and a kind as arguments.
    --- @overload fun(self: Chunks, value: string)
    --- @overload fun(self: Chunks, value: string, position: integer, kind: Chunks.Kind)
    append = function(self, value, position, kind)
        assert(self and value and type(value) == 'string')
        assert((kind and position) or (not kind and not position))
        if not position then
            table.insert(self, value)
        else
            table.insert(self, {value, position, kind})
        end
    end,

}
Chunks.__index = Chunks




--- Generator class.
-- The class that generates the string of Lua code that will be compiled into
-- the function that renders the template.
local Generator = {
    new = function(self)
        local instance = setmetatable({}, self)
        instance.buffer = {}
        return instance
    end,

    result = function(self)
        return table.concat(self.buffer)
    end,

    push = function(self, text, ...)
        table.insert(self.buffer, text)
        if ... then
            self:push(...)
        end
    end,

    header = function(self)
        self:push('local __buffer = ...\n')
    end,

    footer = function(self)
        self:push('return __buffer\n')
    end,

    mark = function(self, pos)
        self:push('--[[', tostring(pos), ']] ')
    end,

    assign = function(self, value)
        self:push('table.insert(__buffer, ', value, ')\n')
    end,

    generate = function(self, chunks)
        self.buffer = {}
        self:header()
        for _, chunk in ipairs(chunks) do
            local kind = type(chunk)
            -- If it's a string, it should be put as a string literal in the
            -- generated code, just escaping the quote symbols using format().
            if kind == 'string' then
                self:assign(('%q'):format(chunk))
            elseif kind == 'table' then
                local value = chunk[1]
                local position = chunk[2]
                kind = chunk[3]

                self:mark(position)
                -- If it's code, it's just added to the buffer, raw.
                if kind == Chunks.CODE then
                    self:push(value, '\n')
                -- Similar to the literal string, but converting to string (and
                -- perhaps escaping).
                elseif kind == Chunks.RAW then
                    self:assign('tostring(' .. value .. ')')
                elseif kind == Chunks.ESCAPE then
                    self:assign('escape(tostring(' .. value .. '))')
                end
            else
                error('unknown type ' .. tostring(kind))
            end
        end
        self:footer()
        return self:result()
    end
}
Generator.__index = Generator



--- @class Parser
elt.Parser = {
    delimiters = {
        open = '<%',
        close = '%>',
        line = '%',
        raw = '=',
        escape = '!',
    },

    new = function()
        return setmetatable({}, elt.Parser)
    end,

    wrap_source = function(source)
        if type(source) == 'string' then
            local position = 1
            return function()
                if position > #source then
                    return nil
                end
                local start, finish = source:find('\r?\n', position)
                if start then
                    local line = source:sub(position, start - 1)
                    position = finish + 1
                    return line
                else -- Return the last line, even if not ended in (CR)LF.
                    local line = source:sub(position)
                    position = #source + 1
                    return line
                end
            end
        elseif type(source) == 'table' then
            -- To prevent silly mistakes, like doing self:wrap_source, and
            -- accidentally passing the Parser instance as source.
            assert(getmetatable(source) ~= elt.Parser, '`wrap_source` does not need a `self`')
            assert(#source == 0 or type(source[1]) == 'string',
                'Source of data for parsing should be a list of strings')
            local current = 0
            return function()
                current = current + 1
                return current <= #source and source[current] or nil
            end
        elseif type(source) == 'function' then
            return source
        else
            error('Parser: unsupported source type. Use a string, table or iterator')
        end
    end,

    parse = function(self, source, delimiters)
        source = self:wrap_source(source)
        return Chunks:new()
    end,
}
elt.Parser.__index = elt.Parser

elt.Chunks = Chunks
elt.Generator = Generator


-- TODO: needs reviewing if it needs more work. It's possible that the function
-- might need to support receving an instance instead of a class (although
-- perhaps the instance accepting a call to `new` is enough!). Also, perhaps the
-- Parser/Generator classes need to support better overriding of functions
-- (overriding at the class level instead of the instance level). But all of
-- this is just a thought. Not confirmed.
elt.compile = function(text, parser_class, generator_class)
    assert(text and type(text) == 'string', 'No template provided or not a string')
    if not parser_class then
        parser_class = Parser
    end
    if not generator_class then
        generator_class = Generator
    end
    local parser = parser_class:new(generator_class:new())
    return parser:compile(text)
end


elt.render = function(text, ...)
    local compiled, message = elt.compile(text)
    if compiled then
        return compiled(...)
    else
        return nil, message
    end
end

return elt

