name: Test and lint the project

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        lua-version: ["5.1", "5.2", "5.3", "luajit-2.1"]

    steps:
      - uses: actions/checkout@v6
      - uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: ${{ matrix.lua-version }}
      - uses: leafo/gh-actions-luarocks@v6
      - name: Install busted
        run: luarocks install busted
      - name: Run tests
        run: busted

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run luacheck
        uses: lunarmodules/luacheck@v1
        with:
            args: src/elt.lua
